<div class="section_row container">
    <h2><?php echo $this->__('Người Dùng Nổi Bật')?></h2>
    <h5><?php echo $this->__('Listed below our awesome team members!')?></h5>
    <div class="circle-box">
        <a href="http://google.com">
            <div class="img_inline text-center center-block our-feat">
                <div class="row_img">
                    <img alt="1" class="img-circle" src="http://gardeniapro.fruitthemes.com/wp-content/uploads/2015/02/home-icon-11-150x150.jpg" width="150" height="150">
                </div>
                <div class="row_content">
                    <h4><?php echo $this->__('Hiep Tran')?></h4>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</p>
                </div>
            </div>
        </a>
    </div>
    <div class="circle-box">
        <a href="http://google.com">
            <div class="img_inline text-center center-block our-feat">
                <div class="row_img">
                    <img alt="2" class="img-circle" src="http://gardeniapro.fruitthemes.com/wp-content/uploads/2015/02/home-icon-21-150x150.jpg" width="150" height="150">
                </div>
                <div class="row_content">
                    <h4><?php echo $this->__('Hiep Tran')?></h4>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</p>
                </div>
            </div>
        </a>
    </div>
    <div class="circle-box">
        <a href="http://google.com">
            <div class="img_inline text-center center-block our-feat">
                <div class="row_img">
                    <img alt="3" class="img-circle" src="http://gardeniapro.fruitthemes.com/wp-content/uploads/2015/02/home-icon-31-150x150.jpg" width="150" height="150">
                </div>
                <div class="row_content">
                    <h4><?php echo $this->__('Hiep Tran')?></h4>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</p>
                </div>
            </div>
        </a>
    </div>
    <div class="circle-box">
        <a href="http://google.com">
            <div class="img_inline text-center center-block our-feat">
                <div class="row_img">
                    <img alt="4" class="img-circle" src="http://gardeniapro.fruitthemes.com/wp-content/uploads/2015/02/home-icon-41-150x150.jpg" width="150" height="150">
                </div>
                <div class="row_content">
                    <h4><?php echo $this->__('Hiep Tran')?></h4>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</p>
                </div>
            </div>
        </a>
    </div>
</div>


<div class="section_row container">
    <h2>Form the blog</h2>
    <h5>we share best articles for garde lowers</h5>
    <div class="fancy_list_wrapper">
        <div class="fancy_list_item">
            <div class="fancy_image">
                <a href="http://gardeniapro.fruitthemes.com/pink-flowers-in-garden/">
                    <img alt="Pink Flowers in Garden" src="http://gardeniapro.fruitthemes.com/wp-content/uploads/2015/02/Portifolio5-350x210.jpg" width="350" height="210">
                </a>
            </div>
            <h4><a class="animate1" href="http://gardeniapro.fruitthemes.com/pink-flowers-in-garden/">Pink Flowers in Garden</a></h4>
            <div class="fancy_categories">
                <div class="fancy_categories">
                    <div><i class="icon-elegant elegant-user"></i><a href="http://gardeniapro.fruitthemes.com/author/admin/" rel="tag">admin</a><i class="icon-elegant elegant-calendar"></i><a href="http://gardeniapro.fruitthemes.com/2015/02/09/" rel="tag"><time datetime="2015-02-09T09:19:20+00:00">February 9, 2015</time></a></div>
                    <div><i class="icon-elegant elegant-comment"></i><span class="comment">4 Comments</span></div>
                    <div class="short-des">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</div>
                    <a class="continue-reading" href="#">Continue reading<i class="icon-elegant elegant-arow"></i></a>
                </div>
            </div>
        </div>
        <div class="fancy_list_item">
            <div class="fancy_image">
                <a href="http://gardeniapro.fruitthemes.com/fort/">
                    <img alt="Fort" src="http://gardeniapro.fruitthemes.com/wp-content/uploads/2015/02/home-icon-31-350x210.jpg" width="350" height="210">
                </a>
            </div>
            <h4><a class="animate1" href="http://gardeniapro.fruitthemes.com/fort/">Fort</a></h4>
            <div class="fancy_categories">

                <div class="fancy_categories">
                    <div><i class="icon-elegant elegant-user"></i><a href="http://gardeniapro.fruitthemes.com/author/admin/" rel="tag">admin</a><i class="icon-elegant elegant-calendar"></i><a href="http://gardeniapro.fruitthemes.com/2015/02/09/" rel="tag"><time datetime="2015-02-09T09:19:20+00:00">February 9, 2015</time></a></div>
                    <div><i class="icon-elegant elegant-comment"></i><span class="comment">4 Comments</span></div>
                    <div class="short-des">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</div>
                    <a class="continue-reading" href="#">Continue reading<i class="icon-elegant elegant-arow"></i></a>
                </div>
            </div>
        </div>
        <div class="fancy_list_item">
            <div class="fancy_image">
                <a href="http://gardeniapro.fruitthemes.com/morning-sky/">
                    <img alt="Morning Sky" src="http://gardeniapro.fruitthemes.com/wp-content/uploads/2015/02/bolg1-350x210.jpg" width="350" height="210">
                </a>
            </div>
            <h4><a class="animate1" href="http://gardeniapro.fruitthemes.com/morning-sky/">Morning Sky</a></h4>
            <div class="fancy_categories">

                <div class="fancy_categories">
                    <div><i class="icon-elegant elegant-user"></i><a href="http://gardeniapro.fruitthemes.com/author/admin/" rel="tag">admin</a><i class="icon-elegant elegant-calendar"></i><a href="http://gardeniapro.fruitthemes.com/2015/02/09/" rel="tag"><time datetime="2015-02-09T09:19:20+00:00">February 9, 2015</time></a></div>
                    <div><i class="icon-elegant elegant-comment"></i><span class="comment">4 Comments</span></div>
                    <div class="short-des">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been</div>
                    <a class="continue-reading" href="#">Continue reading<i class="icon-elegant elegant-arow"></i></a>
                </div>
            </div>
        </div>
    <div class="clear"></div>
</div>
</div>