<?php
//Fetch attribute set id by attribute set name
$attrSetName = 'baiviet';
$attributeSetId = Mage::getModel('eav/entity_attribute_set')
    ->load($attrSetName, 'attribute_set_name')
    ->getAttributeSetId();

$products =$this->getProductCollection()
    ->addFieldToFilter('attribute_set_id', $attributeSetId)->setPageSize();
?>
<?php if(count($products)): ?>
    <div class="new-post">
        <h3><?php echo $this->__('New Post')?></h3>
        <ul>
            <?php foreach ($products as $_link): ?>
                <li>
                    <h4 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>"><?php echo $this->escapeHtml($_link->getName()) ?></a></h4>
                    <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(300,157) ?>" alt="<?php echo $this->escapeHtml($_link->getName()) ?>" />
                    </a>

                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif ?>
